import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import useTranslation from "next-translate/useTranslation";
import Link from "next/link";
import i18nConfig from "../i18n.json";
import { useRouter } from "next/router";

const { locales,defaultLocale } = i18nConfig;

export default function Home() {
  const { t, lang } = useTranslation();
  const router=useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{t("common:greeting")}</h1>
        <div>{t("common:shoppingcart", { number: 15 })}</div>
        <div>Indi istifade olunan dil :{lang}</div>
        <Link href="/about"> Haqqımızda</Link>

        <select onChange={(e)=>{
          const lang=e.target.value=== defaultLocale ? "":e.target.value;
          router.push(`/${lang}`,null, {
            locale: e.target.value
          });
        }}>
        <option>
              {t(`common:language-name-${lang}`)}
            </option>
        {locales.map((lng) => {
          if (lng === lang) return null;

          return (
            <option  value={lng} key={lng}>
              {t(`common:language-name-${lng}`)}
            </option>
          );
        })
        }
        </select>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
